cout << s1.Delete("i") << endl;
    // cout << s1.Delete("j") << endl;
    // cout << s1.Delete("k") << endl;
    // cout << s1.Delete("l") << endl;
    // cout << s1.Delete("m") << endl;
    // cout << s1.Delete("n") << endl;
    // cout << s1.Delete("o") << endl;
    // cout << s1.Delete("p") << endl;
    // cout << s1.Delete("q") << endl;
    // cout << s1.Delete("r") << endl;
    // cout << s1.Delete("s") << endl;
    // cout << s1.Delete("t") << endl;